protected/controllers/AdminController.php
<?php

class AdminController extends RController
{
    public $layout='//layouts/main';

    public function filters()
    {
        return array(
            'rights',
        );
    }


    /**
     * Для администратора - список фрилансеров в формате
     */
    public function actionFreelancers()
    {
        // вытаскиваем всех фрилансеров
        $modelAllFr = Yii::app()->db->createCommand()
            ->select('*')
            ->from('AuthAssignment aa')
            ->join('tbl_users u', 'u.id = aa.userid')
            ->join('tbl_profiles p', 'p.user_id = u.id')
            ->where('aa.itemname = "Freelancer"')
            ->queryAll();

        if ($modelAllFr)
        {
            $data = '';
            foreach ($modelAllFr as $freelancer)
            {
                if ($freelancer['first_name'])
                    $data .= $freelancer['first_name'] . ',' . $freelancer['email'];
                else
                    $data .= $freelancer['username']. ',' . $freelancer['email'];

                $data .= "<br />";
            }
        }

        $this->render('index',array(
            'data'=> $data,
        ));

    }
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{

    public $layout='//layouts/main';

	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
        $modelNews = News::model()->findAll();
        $this->render('index', array('model' => $modelNews));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model = new ContactForm;
		if (isset($_POST['ContactForm']))
		{
			$model->attributes = $_POST['ContactForm'];
			if ($model->validate())
			{
                $data = array(
                    'title' => 'Контактная форма',
                    'name' => $model->name,
                    'email' => $model->email,
                    'message' => $model->body
                );
                $mail = C_Mail::sendContactForm($data);
                if ($mail) {
                    Yii::app()->user->setFlash('contact', 'Спасибо. Ваше сообщение отправлено.');
                } else {
                    Yii::app()->user->setFlash('error', 'Не возможно отправить форму.');
                }

				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}


    public function actionAbout()
    {
        $model = Pages::model()->findByPk(1);
        $this->render('about',array(
            'model' => $model,
        ));
    }

    public function actionFaq()
    {
        $model = Pages::model()->findByPk(2);
        $this->render('faq',array(
            'model' => $model,
        ));
    }


	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return User the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}


	/**
	 * Performs the AJAX validation.
	 * @param User $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>



<div class="col-md-3">
    <div class="box box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Операции</h3>

            <div class="box-tools">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body no-padding">
            <?php
                $this->widget('zii.widgets.CMenu', array(
                    'items'=>$this->menu,
                    'htmlOptions'=>array('class'=>'nav nav-pills nav-stacked'),
                ));
            ?>
        </div>
    </div>
</div>

<?php echo $content; ?>


<?php $this->endContent(); ?>

protected/views/layouts/footer.php
<?php $cs->registerScriptFile($baseUrl .$path_style. '/plugins/jQuery/jquery-2.2.3.min.js'); ?>
<?php $cs->registerScriptFile($baseUrl .$path_style. '/bootstrap/js/bootstrap.min.js'); ?>
<?php $cs->registerScriptFile($baseUrl .$path_style. '/plugins/iCheck/icheck.min.js'); ?>
<?php $cs->registerScriptFile($baseUrl .$path_style. '/plugins/fastclick/fastclick.js'); ?>
<?php $cs->registerScriptFile($baseUrl .$path_style. '/dist/js/app.min.js'); ?>
<?php $cs->registerScriptFile($baseUrl .$path_style. '/dist/js/select2.js'); ?>
<?php $cs->registerScriptFile($baseUrl .$path_style. '/dist/js/icheck.js'); ?>

<!--tags js-->
<?php $cs->registerScriptFile($baseUrl .$path_style. '/dist/js/tags-my.js'); ?>

<?php $cs->registerScriptFile($baseUrl .$path_style. '/dist/js/main.js'); ?>

</body>
</html>

protected/views/layouts/header.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="language" content="en">
    <?php
    $baseUrl = Hp::baseUrl();
    $cs = Hp::cs();
    $path_style = '/css/bootstrap';
    ?>
    <!-- jQuery UI CSS -->
    <?php $cs->registerCssFile($baseUrl . $path_style .  '/bootstrap/css/bootstrap.min.css'); ?>
    <?php $cs->registerCssFile($baseUrl . $path_style .  '/dist/css/select2.css'); ?>
    <?php $cs->registerCssFile($baseUrl . $path_style .  '/dist/css/AdminLTE.min.css'); ?>
    <?php $cs->registerCssFile($baseUrl . $path_style .  '/plugins/iCheck/square/green.css'); ?>

    <?php $cs->registerCssFile($baseUrl . $path_style .  '/dist/css/skins/_all-skins.min.css'); ?>
    <?php $cs->registerCssFile($baseUrl . $path_style .  '/plugins/iCheck/flat/green.css'); ?>
    <?php $cs->registerCssFile($baseUrl . $path_style .  '/dist/css/main.css'); ?>
    <?php $cs->registerCssFile($baseUrl . $path_style .  '/dist/css/tags.css'); ?>
    <?php $cs->registerCssFile($baseUrl .  '/css/custom.css'); ?>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

protected/views/layouts/login_register.php
<?php require('header.php'); ?>
    <div class="login-box">

    <div class="login-logo">
        <span>CRM</span>
        <a href="http://crm.artwebit.ru">
            <img id="u2_img" class="img" src="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap/dist/img/logo.png">
        </a>
    </div>

<?php echo $content; ?>

<?php require('footer.php'); ?>

protected/views/layouts/main2.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="language" content="en">

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print">
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection">
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css">


	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				//array('label'=>'Home', 'url'=>array('/site/index')),
				//array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
				//array('label'=>'Contact', 'url'=>array('/site/contact')),
				//array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				//array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)

                //array('url'=>Yii::app()->getModule('user')->loginUrl, 'label'=>Yii::app()->getModule('user')->t("Login"), 'visible'=>Yii::app()->user->isGuest),
                //array('url'=>Yii::app()->getModule('user')->registrationUrl, 'label'=>Yii::app()->getModule('user')->t("Register"), 'visible'=>Yii::app()->user->isGuest),
                //array('url'=>Yii::app()->getModule('user')->profileUrl, 'label'=>Yii::app()->getModule('user')->t("Profile"), 'visible'=>!Yii::app()->user->isGuest),
                //array('url'=>Yii::app()->getModule('user')->logoutUrl, 'label'=>Yii::app()->getModule('user')->t("Logout").' ('.Yii::app()->user->name.')', 'visible'=>!Yii::app()->user->isGuest),

                array('label'=>Yii::t('app','Home'), 'url'=>array('/site/index')),
                array('label'=>Yii::t('app','About'), 'url'=>array('/site/page', 'view'=>'about')),
                array('label'=>Yii::t('app','Contact'), 'url'=>array('/site/contact')),
                array('label'=>Yii::t('app','Login'), 'url'=>array('/user/login'),'visible'=>Yii::app()->user->isGuest),
                array('label'=>Yii::t('app','Rights'), 'url'=>array('/rights')),
                array('label'=>'Users', 'url'=>array('/user'), 'visible'=>!Yii::app()->user->isGuest),
                array('label'=>Yii::t('app','Logout').' ('.Yii::app()->user->name.')', 'url'=>array('/user/logout'), 'visible'=>!Yii::app()->user->isGuest),


                array('label'=>Yii::t('app','Все проекты'), 'url'=>array('/projects/index')),
                array('label'=>Yii::t('app','Ваши проекты'), 'url'=>array('/projects/myprojects')),


			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->


</body>
</html>

protected/views/layouts/mainmenu.php
<?php //if (!Yii::app()->user->isGuest and (Yii::app()->controller->id !== 'site')) : ?>

<?php
$this->widget('zii.widgets.CMenu', array(
    'htmlOptions' => array(
        'class' => 'nav navbar-nav'
    ),
    'items' => array(

        // Menu for Super Administrator
//        array('label' => 'Роли',                        'url' => array('/rights'),                  'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))),
//        array('label' => 'Список юзеров',               'url' => array('/user'),                    'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))),
//        array('label' => 'Управление юзерами',          'url' => array('/user/admin'),              'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))),
//        array('label' => 'Создать юзера',               'url' => array('/user/admin/create'),       'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))),
//        array('label' => 'Настройка полей',             'url' => array('/user/profileField/admin'), 'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))),
//        array('label' => 'Новости',                     'url' => array('/news'),                    'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))),
//        array('label' => 'Страницы',                    'url' => array('/pages'),                   'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))),







        // Menu for Manager
        array('label' => 'Проекты',
            'url' => array('/projects/indexManager'),
            'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['manager']))
        ),
        array('label' => 'Проекты c заявками',
            'url' => array('/projects/proposal'),
            'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['manager']))
        ),
        array('label' => 'Проекты в работе',
            'url' => array('/projects/active'),
            'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['manager']))
        ),
        array('label' => 'Завершенные',
            'url' => array('/projects/completed'), // архивные/удаленные проекты менеджера
            'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['manager']))
        ),
        array('label' => 'Скрытые проекты',  // неопубликованные,скрытые
            'url' => array('/projects/hidden'),
            'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['manager']))
        ),
        array('label' => 'В корзине',
            'url' => array('/projects/deleted'), // архивные/удаленные проекты менеджера
            'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['manager']))
        ),


        // Общие пункты  меню
        array('label' => 'Главная',
            'url' => '/',
            //'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['manager']))
            'visible' => Yii::app()->user->isGuest
        ),
        array('label' => 'Контакты',
            'url' => array('/site/contact'),
            //'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['manager']))
            'visible' => Yii::app()->user->isGuest
        ),
        array('label' => 'FAQ',
            'url' => array('/site/faq'),
            //'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['manager']))
            'visible' => Yii::app()->user->isGuest
        ),
        array('label' => 'О нас',
            'url' => array('/site/about'),
            //'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['manager']))
            'visible' => Yii::app()->user->isGuest
        ),


        // для фрилансера
        array('label' => 'Проекты',
            'url' => array('/projects/index'),
            'visible' => C_Rights::isFreelancer()
        ),
        array('label' => 'Ваши заказы',
            'url' => array('/projects/offers'),
            'visible' => C_Rights::isFreelancer()
        ),
        array('label' => 'Проекты в работе' . C_User::inJob(),
            'url' => array('/projects/myprojects'),
            'visible' => C_Rights::isFreelancer()
        ),
        array('label' => 'Завершенные',
            'url' => array('/projects/completed'),
            'visible' => C_Rights::isFreelancer()
        ),


        // Common
        //array('label' => 'Выход', 'url' => array('/user/logout')),
    ),
    'encodeLabel' => false,
));
?>
<?php //endif; ?>

protected/views/layouts/sidebar.php
<br/>
<br/>
<br/>

<?php if (Yii::app()->user->isGuest) : ?>
    <ul class="sidebar-menu">
        <li><a href="/user/login"><i class="fa fa-circle-o text-aqua"></i> <span>Войти</span></a></li>
        <li class="header">Зарегистрироваться</li>
        <li><a href="/user/registration?type=freelancer"><i class="fa fa-circle-o text-red"></i><span>Как исполнитель</span></a></li>
        <li><a href="/user/registration?type=manager"><i class="fa fa-circle-o text-red"></i><span>Как менеджер</span></a></li>
    </ul>
<?php endif; ?>

<?php

$admin_menu = array(

    // Menu for Super Administrator
    array(
        'label' => 'Роли',
        'url' => array('/rights'),
        'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))
    ),
    array(
        'label' => 'Список юзеров',
        'url' => array('/user'),
        'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))
    ),
    array(
        'label' => 'Управление юзерами',
        'url' => array('/user/admin'),
        'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))
    ),
    array(
        'label' => 'Создать юзера',
        'url' => array('/user/admin/create'),
        'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))
    ),
    array(
        'label' => 'Настройка полей',
        'url' => array('/user/profileField/admin'),
        'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))
    ),
    array(
        'label' => 'Работа с сайтом',
        'itemOptions' => array('class' => 'header'),
        'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))
    ),
    array(
        'label' => 'Новости',
        'url' => array('/news'),
        'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))
    ),
    array('label' => 'Страницы',
        'url' => array('/pages'),
        'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))),

    array(
        'label' => 'Дополнительно',
        'itemOptions' => array('class' => 'header'),
        'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))
    ),
    array(
        'label' => 'Список фрилансеров',
        'url' => array('/admin/freelancers'),
        'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))
    ),
    array(
        'label' => '--------------',
        'itemOptions' => array('class' => 'header'),
        'visible' => C_Rights::checkRole(array(Yii::app()->params['roles']['admin']))
    ),
);

?>

<?php
    $menu_profile = array (
        array('label'=> '<i class="fa fa-bars"></i><span>Профиль</span>', 'url'=>array('/user/profile')),
        array('label'=> '<i class="fa fa-bars"></i><span>Редактировать профиль</span>', 'url'=>array('/user/profile/edit')),
        array('label'=> '<i class="fa fa-bars"></i><span>Изменить пароль</span>', 'url'=>array('/user/profile/changepassword')),
    );
?>


<?php

    $all_menu = array_merge($admin_menu, $menu_profile, $this->menu);

    $this->widget('zii.widgets.CMenu', array(
        'htmlOptions' => array('class' => 'sidebar-menu'),
        'encodeLabel' => false,

        //'linkLabelWrapper' => 'span',

        'items' => $all_menu

            /*


        )*/
    ));
?>